# Default values for Release Engineering package.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:   pjosephbernard/gsrestservicev2
  tag: 
  pullPolicy: IfNotPresent

service:
  name: gs-rest-service-v2-service
  type: LoadBalancer
  externalPort: "8082"
  externalPortName: expprt
  internalPort: "8082"
  internalPortName: intprt

ingress:
  enabled: false
  hostname: xip.io
  tls:
    secretName: relengv2-tls-dev
    host: relengv2-dev.10.32.84.138.xip.io

resources: 
  limits:
    cpu: "4"
    memory: 4G
  requests:
    cpu: "4"
    memory: 2G
  
  

nodeSelector: {}

tolerations: []

affinity: {}










